OPENAI_API_KEY = "Jouw API Key"
LANGCHAIN_API_KEY = "Jouw API Key"
LANGCHAIN_PROJECT = "Jouw projectnaam"
LANGCHAIN_ENDPOINT = "Jouw Endpoint"
PINECONE_API_KEY = "Jouw API Key"
PINECONE_ENVIRONMENT = "Jou omgeving"
PINECONE_INDEX_NAME = "Jou indexnaam"
GOOGLE_CSE_ID = "XXXX"
GOOGLE_API_KEY = "XXXX"
USERNAME = "XXXX"
SECURITYCODE1 = "XXXX"
SECURITYCODE2 = "XXXX"
RELATIECODE = "XXXX"